title: Nechama O'Brien
description: > # this means to ignore newlines until "baseurl:"
  Nechama O'Brien's technical writing portfolio.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nechama O'Brien # add your name
author-img: profile.jpg # add your photo
about-author: I am a user-centric Technical Writer with experience in SaaS and big data products. # add description
social-twitter: # add your Twitter handle
social-facebook: nechama.obrien # add your Facebook handle
social-github: namaobrien # add your Github handle
social-linkedin: nechamaobrien # add your Linkedin handle
social-email: obrien.nama@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
